### ISSUE TITLE
fix for: PHP Fatal error:  Call to undefined function moodle_major_version()

### ISSUE THREAD

**Issue by elchappo** [oohoo/moodle-block_tts#5]
/var/www/websites/assessment.excelr8learning.co.uk/moodle/blocks/tts/block_tts.php:179

function load_jQuery() {
    global $PAGE;
        $PAGE->requires->css('/blocks/tts/app/_css/jquery.ui.core.css');
        $PAGE->requires->css('/blocks/tts/app/_css/jquery.ui.slider.css');
        $PAGE->requires->css('/blocks/tts/app/_css/jquery.ui.theme.css');

```
    $PAGE->requires->js('/blocks/tts/app/_scripts/jquery-1.6.1.min.js');
    $PAGE->requires->js('/blocks/tts/app/_scripts/jquery.ui.core.js');
    $PAGE->requires->js('/blocks/tts/app/_scripts/jquery.ui.widget.js');
    $PAGE->requires->js('/blocks/tts/app/_scripts/jquery.ui.mouse.js');
    $PAGE->requires->js('/blocks/tts/app/_scripts/jquery.ui.slider.js');
```

}

**Comment by elchappo** [comment]
On moodle version 2.2.11 -> "moodle_major_version" function doesn't exist and you please add check for function maybe http://uk3.php.net/function_exists ?

**Comment by bretin** [comment]
Hi,
Thank you for the notification. I updated the code and submitted a new version on moodle.org

**Comment by elchappo** [comment]
Thanks!
